#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: "true"
#    properties:
#      hibernate:
#        dialect: "org.hibernate.dialect.MySQL5Dialect"
#  database:
#    driverClassName: "com.mysql.jdbc.Driver"
#  datasource:
#    url: "jdbc:mysql://localhost:3306/itemsharingdatabase"
#    username: "root"
#    password: "Rochester24"
#    testWhileIdle: "true"
#    validationQuery: "SELECT 1"
#    
#security:
#  basic:
#    enabled: false
#    
#server:
#  port: 8081
# 

#security:
# oauth2:
#  resource:
#    userInfoUri: http://localhost:8901/user
#    
#signing:
#  key: 345345fsdgsf5345
#  
#logging:
#  level:
#    com.netflix: WARN
#    org.springframework.web: WARN
#    com.itemsharing: DEBUG